### ISSUE TITLE
Issue with babel 7

### ISSUE THREAD

**Issue by Vincz** [FormidableLabs/babel-plugin-transform-define#43]
When we define a config file like that :

    {
        "plugins": [["transform-define", "./config/config.js"]]
    }

We get the following error with babel 7 :

`.plugins[1][1] must be an object, false, or undefined`

**Comment by Vincz** [comment]
What about something like that : https://github.com/Vincz/babel-plugin-transform-define/commit/5ba90a6ad8ba8fc4fa9b791d80409db0b1c3ab3d

Or maybe `__file`  instead of `file`

We cannot use a string as plugin configuration anymore. So we have to use an object even for the file import feature and we need to know if the user want to have an object as config or if he wants to use a config file.

I used to use it like that in my .babelrc :


    "env": {
        "development": {
            "plugins": ["react-hot-loader/babel", ["transform-define", "./config/config.dev.js"]]
        },
        "production": {
            "plugins": [["transform-define", "./config/config.prod.js"]]
        }
    }

**Comment by binary64** [comment]
thanks Vincz, I'm trying to test your fork. I edited my package.json like so: `"babel-plugin-transform-define": "git@github.com:Vincz/babel-plugin-transform-define.git"` and npm install runs fine, but npm run dev kicks up a run-time error:

```
> next

{ Error: Cannot find module 'babel-plugin-transform-define' from 'C:\p\myapp\conf\pods\adminsite'
    at Function.module.exports [as sync] (C:\p\myapp\conf\pods\adminsite\node_modules\resolve\lib\sync.js:40:15)
    at resolveStandardizedName (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\files\plugins.js:78:29)
    at resolvePlugin (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\files\plugins.js:27:10)
    at loadPlugin (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\files\plugins.js:35:18)
    at createDescriptor (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\config-descriptors.js:152:21)
    at C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\config-descriptors.js:104:12
    at Array.map (<anonymous>)
    at createDescriptors (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\config-descriptors.js:103:27)
    at createPluginDescriptors (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\config-descriptors.js:99:10)
    at C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\config-descriptors.js:50:19
    at plugins (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\config-descriptors.js:40:25)
    at mergeChainOpts (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\config-chain.js:296:68)
    at C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\config-chain.js:251:7
    at buildRootChain (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\config-chain.js:85:20)
    at loadPrivatePartialConfig (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\partial.js:41:53)
    at loadPartialConfig (C:\p\myapp\conf\pods\adminsite\node_modules\@babel\core\lib\config\partial.js:66:16) code: 'MODULE_NOT_FOUND' }
```

**Comment by dcalhoun** [comment]
@Vincz I've run into this same issue. Is there a reason you have not opened a PR with your proposed changes? Thanks!

**Comment by Vincz** [comment]
@binary64  You need to compile the package first (run `npm run build` in the module folder).
@dcalhoun The first reason is that it's a breaking change, so it'll break if updated without updating the plugin configuration. The second is that, as we now need to use an object, we cannot really know if the user wants the config object to be the "define" object or if the object contains a path to a file contains the "define" object.

**Comment by Vincz** [comment]
Thank you @xcarpentier !

**Comment by chepelevdi** [comment]
@Vincz  @xcarpentier Hi. Please can you tell me what am I doing wrong?

"devDependencies": {
    "babel-plugin-transform-define": "^1.3.0",
    "babel-plugin-transform-define-file": "^1.3.2",
  }

**.babel.rc**

{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    [
      "transform-define",
      {
        filePath: "./env-config.js"
      }
    ]
  ]
}

**env-config**
const prod = process.env.NODE_ENV === 'production'
module.exports = {
  'process.env.BACKEND_URL': prod ? '/' : 'http://localhost:5000'
}

But in my component console.log('proc', process.env.BACKEND_URL)  - undefined.
It was working in next 5((

**Comment by xcarpentier** [comment]
Hi @chepevdi
You should wait the PR merge but for now you can remove babel-plugin-transform-define and change filePath to file.

**Comment by chepelevdi** [comment]
@xcarpentier tnx a lot

**Comment by nathanqueija** [comment]
Hey, guys.

I managed how to fix that passing an object config to this plugin using .babelrc.js instead of .babelrc:

```
const env = require('./env-config')
module.exports = {
  presets: [['@babel/preset-env', {modules: 'commonjs'}], 'next/babel'],
  plugins: [
    ['lodash'],
    ['transform-define', env],
    ['transform-decorators-legacy'],
    [
      'inline-import',
      {
        extensions: ['.css']
      }
    ],
    [
      'babel-plugin-styled-components',
      {
        ssr: true
      }
    ]
  ],
  env: {
    test: {},
    development: {},
    production: {}
  }
}
```

**Comment by agungsb** [comment]
@nathanqueija 's solution works for me. Thanks, @nathanqueija .. 🎉

**Comment by pmg1989** [comment]
works for me too. Thanks, @nathanqueija
